### ISSUE TITLE
Plugin fails to apply configured syntax highlighting when opening files via CTRL-P

### ISSUE THREAD

**Issue by rnyberg** [execjosh/atom-file-types#13]
OS: Ubuntu 14.04

1) CTRL-P
2) Find a file you've not opened during the session
3) Custom syntax highlighting is not working according to configuration

If I then set the grammar by hand, close the file, then re-open, the syntax is highlighted corrently (for the single file). 

So basicly, I have to reload the editor or manually set the grammar in order to fix the problem every time I open a file I've not previously opened via CTRL-P.

**Comment by davepeck** [comment]
@rnyberg The atom-file-types plugin appears to simply be broken on modern Atom (0.18x and above). See discussion here: https://discuss.atom.io/t/edit-set-file-associations/2650/9?u=davepeck
