### ISSUE TITLE
config not working at all

### ISSUE THREAD

**Issue by danielbayley** [execjosh/atom-file-types#17]
So I have the following in my `config.cson`
```cson
"file-types":
  "jsx(inc)?$": "source.js"
  "style": "source.shell"
```
but it doesn't seem to work at all; `jsx` still open as plain text.

Also, it often randomly removes quotes also like this
```cson
"file-types":
  "jsx(inc)?$": "source.js"
  style: "source.shell"
```
What could be the problem?

**Comment by Rambomst** [comment]
I am also having this issue. Nothing I change seems to have any affect on file type language associations.

This is what I have added to my config.cson
```
"file-types":
  gpx: "text.html.php"
```

**Comment by Rambomst** [comment]
I worked this out. It should look like this in your config.
```
"*":
  "file-types":
    ext: "text.html.php"
```

Well that worked for me at least....

**Comment by mik01aj** [comment]
Thanks, @Rambomst, it worked. The point is, the `file-types` config must be under the `*` in `config.cson`. Would anyone like to make a PR with the README change to clarify this?

**Comment by execjosh** [comment]
Does this work with v0.4.0?

**Comment by danielbayley** [comment]
Something has been broken for a while. I have the following in my `config.cson`, but none of it works at all;

```cson
"file-types":
    "jsx(inc)?$": "source.js"
    ffx: "source.js"
    ".*htaccess.*": "source.apache-config"
    "bash[r_]*": "source.shell"
    "var(iable)?s.(md|txt)": "source.shell"
    "^hosts$": "source.shell"
    sdef: "text.xml"
    style$: "source.shell"
```

Only if I have the following 'fix' in my `init.coffee` does anything work;

```coffeescript
atom.workspace.observeTextEditors (editor) ->
   path = editor.getPath()
   return unless path?

   fileTypes =
      'jsx': 'source.js',
      'jsxinc': 'source.js',
      'ffx': 'source.js',
      'hataccess.md': 'source.js',
      'htaccesss.txt': 'source.js',
      'variables.md': 'source.shell',
      'hosts': 'source.shell',
      'sdef': 'text.xml',
      'style': 'source.shell'

   for extension of fileTypes when path.toLowerCase().endsWith(extension.toLowerCase()) and (longestExtension ? "").length < extension.length
      longestExtension = extension

   return unless longestExtension?
   g = atom.grammars.grammarForScopeName fileTypes[longestExtension]
   return unless g?
   editor.setGrammar g
```

RegEx don't seem to work in this context either. Hope this is enough info for a fix.

**Comment by carlcs** [comment]
Update to 0.4.0 and Atom 0.207 broke the package for me.

**Comment by nicholasanderson** [comment]
I definitely believe specifying that it belongs under root "*": in the README.md would be beneficial. I wondered the same thing until I found this issue.

**Comment by danielbayley** [comment]
That doesn't make it work though.

**Comment by nicholasanderson** [comment]
agreed. i just retested with 0.4.0 and atom 0.207.0 and it is non-functional.

**Comment by danielbayley** [comment]
Working well now. Nice one!

**Comment by execjosh** [comment]
:thumbsup:
