### ISSUE TITLE
Package non-functional for atom 1.0.2

### ISSUE THREAD

**Issue by stewhouston** [execjosh/atom-file-types#33]
Non-functional code in config.cson:
```
"*":
  "file-types":
    jhtml: "text.html"
```

**Comment by hbrls** [comment]
+1 for Atom 1.0.0

    jsx: "source.js.jsx.myjs"

**Comment by execjosh** [comment]
You are using an invalid scope name.

![image](https://cloud.githubusercontent.com/assets/189989/8854041/cc67bbfa-3198-11e5-9b9c-3c6e56650416.png)

The [language-html](https://atom.io/packages/language-html) package provides the scope `text.html.basic`.  The scope `text.html` *does not exist*.

Please ensure the scope you are setting *actually* exists.

![image](https://cloud.githubusercontent.com/assets/189989/8854167/84e36800-3199-11e5-849d-f2d82dd982e3.png)

**Comment by hbrls** [comment]
But I had them.

![screen shot](https://cloud.githubusercontent.com/assets/1220476/8866309/5faf336c-31ed-11e5-945c-b6fa6ceed927.png)

**Comment by execjosh** [comment]
What package provides that grammar?

**Comment by execjosh** [comment]
What package is providing that scopeName?

**Comment by hbrls** [comment]
1. language javascript, on atom
2. react, on atom
3. my customized language js, not public yet

what do you think of I should try to debug?

**Comment by execjosh** [comment]
I don't know, exactly.  Maybe language-react is "winning" by registering `jsx` later than your package?  Please make a new issue and we can work it out there... (and link back to this issue :wink: )

**Comment by execjosh** [comment]
I think I found the problem.  Continuing over in issue #34.
