### ISSUE TITLE
Apparently a timing issues cause grammar not to be applied

### ISSUE THREAD

**Issue by execjosh** [execjosh/atom-file-types#34]
It's hard to reproduce; but, there are some instances where a grammar cannot be gotten.  This looks to be an issue where the logic is run before the grammars have actually been loaded.

**Comment by execjosh** [comment]
@hbrls Does v0.4.2 fix your problem?

**Comment by hbrls** [comment]
@execjosh no, I'm now with v0.5.1

What debug log do you want?

**Comment by execjosh** [comment]
Turn on debug mode for the file-types package, either directly in your config.cson (by adding `$debug: yes`) or through the package settings window.  Then open the developer tools (`option + command + i` on OS X) and see what is displayed.  You can reload everything with `control + option + command + l` (on OS X) and watch the log.  There should be a message for each editor open and when new editors are opened, config changed, etc.

**Comment by hbrls** [comment]
for .js

    [file-types] setting source.js.jsx.myjs as grammar for activity.js

for .jsx

    [file-types] setting source.js.jsx.myjs as grammar for file_input.jsx

but the text on right bottom is still `JavaScript (JSX)`

**Comment by execjosh** [comment]
Hmm...  So, it looks like it's setting it; but, then it's being overridden.  Hmm...

**Comment by execjosh** [comment]
Apparently there's a "grammar used" event (see [`TokenizedBuffer`](https://github.com/atom/atom/blob/v1.0.3/src/tokenized-buffer.coffee#L106).  Can you add a handler for that to your grammar and see what happens?  There might also be some other "grammar unused" kind of event...

**Comment by hbrls** [comment]
'name': 'My JavaScript'
    'packageName': 'MyJavaScript'

changes nothing.

**Comment by hbrls** [comment]
Another interesting finding:

1. open a.jsx
2. handle as `React`
3. leave that tab open
4. open atom settings -> package -> file-type
5. check `$debug` and the a.jsx on background is set to `My JavaScript`

I think the `$debug` switch reload your file-type package and output the correct behavior.

**Comment by execjosh** [comment]
I'm going to set this as resolved by #44, which moved editor processing to after all packages have been loaded.  Please feel free to reopen it if this problem is still reproducible for you.
