### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by alexchandel** [execjosh/atom-file-types#35]
`30ms` is unusually long, considering my other packages range from `1ms` to `5ms`.

**Comment by execjosh** [comment]
Thank you for bringing this to my attention.  I'll look into the reason :+1:

**Comment by execjosh** [comment]
I have been able to move the config loading, etc. to the next tick (`process.nextTick`) and got it down to around 5ms.

**Comment by alexchandel** [comment]
Nice. But does this mean it still slows down startup, it just can't be seen?

**Comment by execjosh** [comment]
Well, the debug messages come after `Window load time: 1614ms`; so, that makes me think it actually is faster.

Unfortunately, this package must loop through each editor and look at the path to decide proper grammar (there are different events that necessitate another look).  As such, it attaches to those events upon activation, which is what causes the "long load time", which should {de,in}crease depending on how many windows Atom remembers for you at startup.

Do you know of any event triggered once Atom has been loaded (like DOMReady kind of thing)?  If so, then the package could just listen for that event and then add the respective event listeners at that time.

**Comment by Alhadis** [comment]
Use `atom.packages.onDidActivateInitialPackages` to specify a callback that should run only when every package has finished initialising on startup.

**Comment by execjosh** [comment]
I will check into that.  Thank you.

**Comment by execjosh** [comment]
I released v0.5.2.  I'm confident it has solved this issue.
