### ISSUE TITLE
Match against whole path instead of only basename

### ISSUE THREAD

**Issue by astrumas** [execjosh/atom-file-types#36]
Forgive me if this functionality already exists and I just don't understand how I would go about it utilizing it.

I am using Ansible and some of the files are in Ansible's YAML format, but do not have an extension or I do not want it to default to using the base YAML syntax.

I am basically looking for the functionality that exists in the ApplySyntax plugin for Sublime.  A direct example would be: http://jamie.ideasasylum.com/2014/08/ansible-syntax-highlighting-sublime/

Is this currently possible with this package? If so, how would I go about duplicating the settings as depicted in that link?

**Comment by execjosh** [comment]
Currently, this package only looks at the file name.  If I understand correctly, you want to have a regexp be applied to the whole path.  Is that correct?

**Comment by astrumas** [comment]
Yes, that is correct.

**Comment by execjosh** [comment]
Thank you for confirming :)  Matching against the whole path is currently unavailable; but, I can see you have a valid use case.  There are some other tasks that need to be done before I can move on to this one; but, contributions are always welcome!

**Comment by rscarvalho** [comment]
:+1: for support. I have the same use case with ansible files

**Comment by mishak87** [comment]
@execjosh Do you need some help with this? I just finished my first atom-extension and would gladly help.

**Comment by execjosh** [comment]
@mishak87  Pull requests are always welcome!  If you have the time, then by all means!

**Comment by mishak87** [comment]
@execjosh Is something blocking this feature or can I get directly to it?

**Comment by execjosh** [comment]
I definitely want to get this in the next "big" release; but, we need to decide, as a community, how we want to configure the file types.  Please have a gander at #49.

**Comment by nklmilojevic** [comment]
Is there any update about this or is the project dead?

**Comment by execjosh** [comment]
Only me working in spare time 😉  👋

**Comment by nklmilojevic** [comment]
I'll gladly help because this is the only thing keeping me from fully switching from SublimeText and its ApplySynthax plugin. :)
