### ISSUE TITLE
Associate '_spec.rb' with RSpec

### ISSUE THREAD

**Issue by evmorov** [execjosh/atom-file-types#37]
Hello!
I'm trying to do this association but have no idea what is going wrong. My config:

```cson
"file-types":
  '_spec\.rb$': 'source.rspec'
  rb: "source.ruby"
```

Any suggestions?

**Comment by execjosh** [comment]
Hi, thanks for your question.

Is this under the `"*"` section of your config?

**Comment by Evmorov** [comment]
@execjosh yeap! Maybe I should write not 'source.rspec' but something else? Any ideas where to look?

**Comment by Evmorov** [comment]
I also tried like this but it didn't help
```cson
  "file-types":
    '_spec\.rb$': 'source.ruby.rspec'
    rb: "source.ruby"
```

**Comment by execjosh** [comment]
I just tried this in atom 1.6.0 and it works.  I'm going to close this as irreproducible.  Please reopen it if you're still having problems.

```cson
"*":
  "file-types":
    "_spec\.rb$": "source.ruby.rspec"
```

**Comment by execjosh** [comment]
Wait, I see.  The ruby scope is winning, right?

**Comment by evmorov** [comment]
@execjosh I guess so. I'm on 1.6.0 and it's still not working for me.

**Comment by execjosh** [comment]
When you remove `rb: "source.ruby"`, then it works, right?

**Comment by evmorov** [comment]
I've figured out!
It should be (without 'rb: "source.ruby"'):
```
"file-types":
    '_spec\.rb$': 'source.ruby.rspec'
```
Thanks!

**Comment by execjosh** [comment]
Great :smile:
