### ISSUE TITLE
How to get list of current assignments of file-type extension to grammars?

### ISSUE THREAD

**Issue by dannguyen** [execjosh/atom-file-types#43]
What's the easiest way to find where, by default, file extensions are associated to a grammar file name?

To be honest, all I want to know is what the heck is the grammar file name for Github flavored markdown...I'm trying to do something like this:

```cson
  "file-types":
    "html.md.erb": "text.github-markdown"  # this doesn't work..what name should I use instead?
```

But I should probably know more of the internals of the Atom system :)

**Comment by execjosh** [comment]
This is outlined in the [Scope Names][1] section of the README.  Its language might still be too technical; so, any help with rewording would be much appreciated!

Packages that provide highlighting usually start with `language-` as their name.  You can look at their settings to see what is provided.

Which package handles GHFMD for you?

[1]: https://github.com/execjosh/atom-file-types/blob/master/README.md#scope-names

**Comment by execjosh** [comment]
Just a quick look landed me on [language-gfm][1], which provides the scope, [`source.gfm`][2].  This is probably what you're after.

[1]: https://github.com/atom/language-gfm
[2]: https://github.com/atom/language-gfm/blob/master/grammars/gfm.cson#L2

**Comment by dannguyen** [comment]
@execjosh that was beautifully simple...yet the pedant in me feels like they should have put it as text-gfm where I would've more easily noticed it :). Thanks!

**Comment by execjosh** [comment]
Glad you've solved your question!  Happy usage :wave:

**Comment by execjosh** [comment]
By the way, there is a section in the flight manual about [finding a language's scope name][1], too.  Just for future reference.

[1]: http://flight-manual.atom.io/using-atom/sections/basic-customization/#_finding_the_language_scope_name
