### ISSUE TITLE
Good plugin, bad example.

### ISSUE THREAD

**Issue by ysyfff** [execjosh/atom-file-types#45]
Why the example is bad? Because 'text.html.htmlbars' not exists in most atom.
Use `'string(or something else)': 'text.html.basic'` shuold be better.

**Comment by execjosh** [comment]
I'm not sure I understand the problem.

**Comment by execjosh** [comment]
If other people feel the documentation is unclear in this area, too, then feel free to reopen this and we can work to make it better 😄

**Comment by guzart** [comment]
Am new to babel configurations, so am struggling into finding the name I need for the configuration, am trying to match the ".react" extension to the "language-babel", I just don't know where to find the `text.html.htmlbars` equivalent

**Comment by execjosh** [comment]
Please read about [finding a language's scope name][1]

[1]: http://flight-manual.atom.io/using-atom/sections/basic-customization/#finding-a-languages-scope-name
