### ISSUE TITLE
Can I avoid auto rewrite/format of rules ?

### ISSUE THREAD

**Issue by inohiro** [execjosh/atom-file-types#46]
file-types plugin is really usful for me. Thank you :)

But mostly, probably when start or terminate Atom or open setting screen, 
my file-types rules will be overwritten.

I'm using regexp rule that will be disabled if order is changed.
Like this diff: 

```diff
@@ -18,15 +18,22 @@
   "file-types":
-    ct: "source.sql"
-    ".sql.job$": "source.sql"
     ".job$": "source.yaml"
+    ".sql.job$": "source.sql"
+    ct: "source.sql"
```
So can I avoid auto rewrite/format of rules ?

**Comment by execjosh** [comment]
Thank you for using it!  Glad to hear it's useful for you.

Hmm, this is interesting.  The reformatting is done by atom itself; so, probably not.

As for precedence, I think there is some issue where longest-match was discussed.  It hasn't been implemented yet, though.

**Comment by execjosh** [comment]
Ah, issue #5

**Comment by inohiro** [comment]
I see! The root problem of my situation, it's not reformatting (by Atom) but matching priority.
It seems the longest match strategy will work on my situation.

**Comment by execjosh** [comment]
@inohiro Does v0.5.3 fix your issue?

**Comment by inohiro** [comment]
@execjosh v0.5.3 works fine! Thank you (I also tried to make a patch, but it wasn't easy to me 😫
