### ISSUE TITLE
Bash-like Globbing

### ISSUE THREAD

**Issue by execjosh** [execjosh/atom-file-types#49]
**QUESTIONS for the COMMUNITY**

What say ye?
- Is RegExp overkill?
- Would bash-like globbing be a better way to configure your file types?
- How could we transition from the current way of configuring?

"I'm verklempt.  Speak amongst yourselves."

---

My thoughts:
- Bash-like globbing is simple
- It is easy and familiar to specify and understand
- A breaking change is probably fine as long as most people know about it ahead of time
  - Need some kind of notification inside the package, probably

**Comment by execjosh** [comment]
Well, I started an implementation...

**Comment by execjosh** [comment]
Sooo...  No thoughts from the community...?

**Comment by execjosh** [comment]
I suppose, then, it'll be best to make an interim, deprecated-but-still-useable-as-is term to ease transition.  I will update this pr.

**Comment by mishak87** [comment]
I would just show how to migrate rules notification if user has already some rules defined. Maybe tag next as 1.0 so it is clear it is a firm decision to go with bash glob instead of regex. Just my :two: cents.

Thanks!

**Comment by execjosh** [comment]
Thank you very much for your 2¢!  The more the merrier :)

I have, actually, been toying with the idea of showing a notification, because I don't want to just break everyone's settings all of a sudden—that's not very nice ;)

And I do agree that cutting 1.0 as soon as possible is a good idea :)

I'm thinking of first deploying a pre-release version able to handle both formats (assuming globbing but defaulting to current behaviour) that would display a notification (and maybe even stating a planned deadline).  Then, after some interval, the actual 1.0 that would completely remove the notification and interpret everything as glob could be released.

However, _Extension Matchers_, being a subset of globs (i.e., no wildcards), are difficult to discern from regular globs.  _RegExp Matchers_ could be valid globs but have a different meaning.  So, there's a little dilemma as to deciding whether the user has updated to globs or not.  I suppose moving the settings to a separate key in the config could mitigate that; but, is _another_ key even worth it?  I dunno...  I'm probably over analyzing...

Thanks again for your thoughts.  I had hoped to have a larger discussion.  Please feel free to give more thoughts ;)

**Comment by mishak87** [comment]
I think there should be only glob as official matching in 1.0 that way it is simple and not confusing. Extensions are just shortcut for `*<ext>` (feature just for one extra character).
No key for rules (rules mixed with settings) was bit confusing for me at the start maybe putting all globs into rules key and supporting rest silently as is might be an option.
