### ISSUE TITLE
Add tie-breaker logic for similar extensions

### ISSUE THREAD

**Issue by chrisdchristo** [execjosh/atom-file-types#5]
Is it possible to support the following:

for e.g:
```
'file-types':
  'css.liquid': 'source.css'
  'scss.liquid': 'source.css.scss'
  'liquid': 'text.html.basic'
```

Currently, with the above setting, files ending in .css.liquid and .scss.liquid will show up as HTML. I'm guessing this is because the final line overrides the previous.

**Comment by execjosh** [comment]
Still haven't investigated.  But, I think we need tie-breaker (e.g., longest match or something)...

**Comment by chrischristo** [comment]
I think the more sublevels should win. i.e 'scss.liquid' beats 'liquid'.

**Comment by execjosh** [comment]
I think longest match is the most logical solution.

i.e., in `scss.liquid` vs `css.liquid`, `scss.liquid` should win.

**Comment by execjosh** [comment]
@chrisdchristo Hopefully v0.5.3 takes care of your issue.

**Comment by execjosh** [comment]
BTW, it will show a warning for the case when there are multiple "longest" matches, and use the last of the list, sorted alphabetically by the match itself.  Usually the match is the same, though 🙈 

![image](https://cloud.githubusercontent.com/assets/189989/17079947/56728ad2-515a-11e6-9262-af03b835d4f4.png)
