### ISSUE TITLE
path.basename is deprecated.

### ISSUE THREAD

**Issue by dflock** [execjosh/atom-file-types#52]
This is the output from deprecation-cop:

Arguments to `path.basename` must be strings
```
path.basename (/usr/share/atom-beta/resources/app.asar/src/electron-shims.js:31:10)
Object._tryToSetGrammar (/home/duncan/.atom/packages/file-types/lib/file-types.coffee:118:18)
<unknown> (/home/duncan/.atom/packages/file-types/lib/file-types.coffee:87:24)
<unknown> (/usr/share/atom-beta/resources/app.asar/src/workspace.js:334:16)
Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
Emitter.emit (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
```

**Comment by execjosh** [comment]
Oh, thanks! 🤔  I'll look into it.

**Comment by SwankyLynx** [comment]
The same here after update Atom to 1.13

**Comment by execjosh** [comment]
I'm not able to reproduce this with Atom 1.13.0 (i.e., I get no warnings in Deprecation Cop).  Would it be possible for you to post a screen capture, too?  Maybe this is a platform-dependent thing???

![image](https://cloud.githubusercontent.com/assets/189989/21991134/bfdf9688-dc54-11e6-9055-56b4f0357322.png)

**Comment by otroboe** [comment]
I have the issue too, on Xubuntu 16.04.1, with Atom 1.13.0

![file-types-issue](https://cloud.githubusercontent.com/assets/12752852/21992894/422a8dba-dbe6-11e6-9a35-6652f06aa4f3.png)

**Comment by execjosh** [comment]
Thanks!  I wonder why this is not triggering on Mac...

**Comment by execjosh** [comment]
I suppose that I should confirm what version is everyone using.  The line numbers don't seem to match up with the current version (v0.5.4-p1).

**Comment by execjosh** [comment]
I threw in a `require('grim').deprecate('aaah')` at line 70 (first line of `_tryToSetGrammar`) and it shows file-types.coffee `118:23`, `77:32`, and `69:34` in Deprecation Cop.

**Comment by SwankyLynx** [comment]
Mac OS X Sierra 10.12.2 (16C67), Atom 1.13.0 x64
![capturfiles-20170116_222103](https://cloud.githubusercontent.com/assets/25042137/21994679/67aaba5c-dc3a-11e6-83ac-90525d0d2cc5.png)

**Comment by execjosh** [comment]
I'm using:
- macOS Sierra 10.12.2 (16C68)
- Atom 1.13.0 x64
- file-types v0.5.4-p1

And unable to reproduce 🤔

**Comment by otroboe** [comment]
It's strange, the error doesn't show up in my main app window, but appears in a new window (Ctrl+Shift+N) (File->New Window).

**Comment by execjosh** [comment]
OKAY!  I just reproduced it!  It happens when a new, unsaved buffer is opened (i.e., it doesn't have a path yet).  It looks like @otroboe got it, too.

https://github.com/atom/atom/blob/96111f47e973dd737e68ecb0708f1a08f5711c0d/src/text-editor.coffee#L817

**Comment by sidx64** [comment]
Greetings!

Just got this deprecation notice:
![Screenshot of Deprecation Notice](https://i.imgur.com/1UkmB2B.png)

OS: MacOSX 10.13 [High Sierra]
Atom Version: 1.32.2 x64

**Comment by BhautikDonga** [comment]
![deprecation cop c__users(https://user-images.githubusercontent.com/34915439/49385696-03e55c80-f744-11e8-98b9-21e965544e97.png)
in windows 10

**Comment by BhautikDonga** [comment]
in windows 10
i get this error
![deprecation cop c__users_(https://user-images.githubusercontent.com/34915439/49385844-4b6be880-f744-11e8-9070-1f87ff74ee19.png)

**Comment by Pvanduyse** [comment]
![depreciated](https://user-images.githubusercontent.com/7491272/99193549-c10dcb00-2747-11eb-98d5-2399adee5fe8.png)
Version 1.53.0, Windows 10
I know it's been a couple of years, but this just showed up again. Brand new install of Atom, first thing I noticed (before even opening up a file or looking at the settings.)

**Comment by EmediongFrancis** [comment]
I am not so sure of this solution, it might need further testing in case there are other variables involved. 
I faced this issue and all I did was initialize my git repository from Git Bash and the error disappeared.

**Comment by lw-lonewolf** [comment]
Im getting this error on atom 1.13.2 x64 and windows 8.1 
![image](https://user-images.githubusercontent.com/86514248/124343138-35ce3200-db7e-11eb-8f29-0bc727a1d313.png)

**Comment by mzayn** [comment]
> Im getting this error on atom 1.13.2 x64 and windows 8.1
> ![image](https://user-images.githubusercontent.com/86514248/124343138-35ce3200-db7e-11eb-8f29-0bc727a1d313.png)

+1 same issue
