### ISSUE TITLE
What would be the rule for a .babelrc + json file ?

### ISSUE THREAD

**Issue by ChrisRast** [execjosh/atom-file-types#55]
Hi,
I was just wondering how I could apply JSON file type to all ".{something}rc" files. (Except from manually chosing it each time.)

For example:
- .babelrc
- .eslintrc
- .remarkrc

Are they recognized as babelrc type, or without type ?
Thank you for your help.

**Comment by execjosh** [comment]
At present, you could use a RegExp Matcher.  Does that work for your needs?

**Comment by ChrisRast** [comment]
Hi, I finally answer!
Yes, it works. Here is the piece of `cson` I wrote:
```cson
  "file-types":
    ".(.*)rc": "source.json"
```
Thank you for this package. Have a good day!
