### ISSUE TITLE
Matchers with a . break when restoring settings with sync-settings

### ISSUE THREAD

**Issue by jpeltoniemi** [execjosh/atom-file-types#56]
Relevant issue in sync-settings: [Broken settings on restore when using a . in property names #358](https://github.com/atom-community/sync-settings/issues/358)

Seems that dot is used internally to separate config value paths, which causes certain filename matchers to break.

From config.cson
```
  "file-types":
    html: "text.html.js"
    "^[^\\.]+$": "source.shell"            (A: Original regex, doesn't work)
    "^[\\w\\d\\-_]+$": "source.shell"      (B: New regex, works)
```

I noticed this when config.cson kept breaking after sync when I used regex A. After switching to regex B everything works as expected.

Can't really say what should be done to maximize compatibility, but I thought you'd like to be informed.

**Comment by execjosh** [comment]
Thank you for opening the issues.  Not sure what to do, either... 🤔

**Comment by execjosh** [comment]
I'm going to close this for now because I have no clue what to do.
