### ISSUE TITLE
nothing works

### ISSUE THREAD

**Issue by DanLegacy** [execjosh/atom-file-types#59]
After I installed this package, I closed and restarted many times but the package name did not appear in the Packages Tab and everywhere else.

**Comment by execjosh** [comment]
I'm sorry to hear this.  Thank you for the bringing it to my attention.

I will attempt to reproduce the problem; however, "it doesn't work" is extremely vague.  Could you please provide as much information about your environment as possible?  Atom version, OS, etc. would be very helpful.

Additionally, what were you expecting to happen and what actually happened?

Thanks!

**Comment by dborstelmann** [comment]
@execjosh It doesn't work for me either after following the readme.  The file types just don't update.  This solved it for me and seems to duplicate functionality of this package:  http://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-language-recognition

**Comment by execjosh** [comment]
I still have not had time to look into this issue...

This package was created when there was no functionality in the core for this kind of thing.  Maybe they have implemented it fully? 🤔

**Comment by execjosh** [comment]
It works for me.  Please reopen if you still are having problems.

**Comment by dborstelmann** [comment]
👍  I forget what I did here but I think I am using the built in stuff
