### ISSUE TITLE
Disable errors syntax highlighting when use mustache js system in html document

### ISSUE THREAD

**Issue by Raf-sns** [execjosh/atom-file-types#61]
Hello, 
i have a big orange syntax error when i use mustache in a html document,
how can i fix it ?
Thnx for your help !
see:
![bugat](https://user-images.githubusercontent.com/36576486/37711586-7dc1d3b0-2d11-11e8-9b75-c03e235a695a.JPG)

i try html for msutache, no works ...

**Comment by execjosh** [comment]
Hello.

Maybe I've misunderstood your question; but, this package exists only to allow one to specify a certain language (grammar) for a certain file type.  If a specific language (grammar) does not work as expected, you will need to open an issue with that project.

**Comment by Raf-sns** [comment]
Ok, i understood, thank you
