### ISSUE TITLE
unable to match a file without an extension

### ISSUE THREAD

**Issue by kidbrax** [execjosh/atom-file-types#63]
what would the pattern be to match these files? I can't seem to get any to work. They do not have extensions.

Dockerfile-one
Dockerfile-two

I have tried this: "^Dockerfile*$": "source.dockerfile"

**Comment by execjosh** [comment]
Haven't tried it but that regex would mean `Dockerfil` `Dockerfile` `Dockerfileeeeeeeeee` etc., I think.

Perhaps you should use something like `^Dockerfile.*$` 🤔

**Comment by execjosh** [comment]
You can now use `"Dockerfile*": "source.dockerfile"` with v1.0.0 🎉

**Comment by execjosh** [comment]
Please reopen if you are still unable to get it working 👍
